"use client";

import * as React from "react";
import { PublicShell } from "@/components/public/PublicShell";
import { PublicPageHeader } from "@/components/public/PublicPageHeader";
import { Card } from "@/components/ui/linear";
import type { Locale } from "@/i18n/LocaleContext";

interface Strings {
  title: string;
  intro: string;
  reportHeading: string;
  reportBody: React.ReactNode;
  slaHeading: string;
  slaIntro: string;
  slaRows: ReadonlyArray<{ stage: string; target: string }>;
  severityHeading: string;
  severityIntro: string;
  severityRows: ReadonlyArray<{
    cvss: string;
    severity: string;
    patch: string;
  }>;
  safeHarborHeading: string;
  safeHarborBody: React.ReactNode;
  outOfScopeHeading: string;
  outOfScopeItems: ReadonlyArray<string>;
  rewardHeading: string;
  rewardBody: React.ReactNode;
  morePolicyHref: string;
  morePolicyLabel: string;
  securityTxtHref: string;
  securityTxtLabel: string;
  hallOfFameHref: string;
  hallOfFameLabel: string;
}

const COPY: Record<Locale, Strings> = {
  en: {
    title: "Security Policy",
    intro:
      "CoreLink runs a coordinated vulnerability disclosure program. This page is the customer-facing summary; the full legally binding text lives in our spec repository (linked at the bottom).",
    reportHeading: "How to report",
    reportBody: (
      <>
        <p>
          Email <code>security@humangr.com</code> with the subject prefix{" "}
          <code>[VULN]</code>. For high-impact issues, please encrypt with our
          PGP key.
        </p>
        <p>
          There is no web form: email is the only intake channel.
        </p>
      </>
    ),
    slaHeading: "Response SLA",
    slaIntro:
      "Times are calendar hours/days from receipt of a well-formed report.",
    slaRows: [
      { stage: "Acknowledge receipt", target: "within 24 hours" },
      { stage: "Initial triage", target: "within 72 hours" },
      { stage: "Status updates", target: "every 7 days" },
      { stage: "Public credit (if desired)", target: "at coordinated disclosure" },
    ],
    severityHeading: "Severity & patch SLA",
    severityIntro:
      "Severity is mapped from CVSS v3.1 Base score, with auto-escalation for tenant-isolation violations.",
    severityRows: [
      { cvss: "9.0 – 10.0", severity: "CRITICAL", patch: "≤ 24 hours" },
      { cvss: "7.0 – 8.9", severity: "HIGH", patch: "≤ 7 days" },
      { cvss: "4.0 – 6.9", severity: "MEDIUM", patch: "≤ 30 days" },
      { cvss: "0.1 – 3.9", severity: "LOW", patch: "≤ 90 days" },
    ],
    safeHarborHeading: "Safe harbor",
    safeHarborBody: (
      <p>
        We will not pursue legal action against researchers acting in good
        faith who avoid privacy violations, only interact with accounts they
        own, do not exploit beyond proof-of-concept, and give us reasonable
        time to fix before disclosing. Full language in the spec.
      </p>
    ),
    outOfScopeHeading: "Out of scope",
    outOfScopeItems: [
      "Denial-of-service against production",
      "Social engineering of staff or customers",
      "Physical attacks",
      "Theoretical findings without a proof-of-concept",
      "Reports generated by automated scanners with no human analysis",
      "Issues in third-party dependencies (report to the vendor)",
    ],
    rewardHeading: "Reward program",
    rewardBody: (
      <p>
        Pre-GA: thank-you in the changelog, Hall of Fame credit, and CoreLink
        swag for MEDIUM+ findings. Monetary bounty program is planned post-GA.
      </p>
    ),
    morePolicyHref:
      "https://github.com/HumanGuardrail/corelink/blob/main/specs/_security/vulnerability-disclosure-policy.md",
    morePolicyLabel: "Read the full policy (VDP-001)",
    securityTxtHref: "/.well-known/security.txt",
    securityTxtLabel: "security.txt (RFC 9116)",
    hallOfFameHref: "/security/hall-of-fame",
    hallOfFameLabel: "Hall of Fame",
  },
  pt: {
    title: "Política de Segurança",
    intro:
      "A CoreLink mantém um programa de divulgação coordenada de vulnerabilidades. Esta página é o resumo voltado ao cliente; o texto legal completo vive no nosso repositório de specs (link abaixo).",
    reportHeading: "Como reportar",
    reportBody: (
      <>
        <p>
          Envie e-mail para <code>security@humangr.com</code> com o prefixo{" "}
          <code>[VULN]</code> no assunto. Para problemas de alto impacto,
          criptografe com nossa chave PGP.
        </p>
        <p>
          Não há formulário web: o e-mail é o único canal de recebimento.
        </p>
      </>
    ),
    slaHeading: "SLA de resposta",
    slaIntro:
      "Tempos contados em horas/dias corridos a partir do recebimento de um report bem-formado.",
    slaRows: [
      { stage: "Confirmação de recebimento", target: "em até 24 horas" },
      { stage: "Triagem inicial", target: "em até 72 horas" },
      { stage: "Atualizações de status", target: "a cada 7 dias" },
      { stage: "Crédito público (se desejado)", target: "na divulgação coordenada" },
    ],
    severityHeading: "Severidade & SLA de correção",
    severityIntro:
      "Severidade mapeada a partir do CVSS v3.1 Base, com escalada automática para violações de isolamento de tenant.",
    severityRows: [
      { cvss: "9.0 – 10.0", severity: "CRÍTICA", patch: "≤ 24 horas" },
      { cvss: "7.0 – 8.9", severity: "ALTA", patch: "≤ 7 dias" },
      { cvss: "4.0 – 6.9", severity: "MÉDIA", patch: "≤ 30 dias" },
      { cvss: "0.1 – 3.9", severity: "BAIXA", patch: "≤ 90 dias" },
    ],
    safeHarborHeading: "Safe harbor",
    safeHarborBody: (
      <p>
        Não tomaremos medidas legais contra pesquisadores agindo de boa-fé,
        que evitem violações de privacidade, interajam apenas com contas
        próprias, não explorem além do PoC e nos dêem tempo razoável para
        corrigir antes da divulgação pública.
      </p>
    ),
    outOfScopeHeading: "Fora de escopo",
    outOfScopeItems: [
      "Ataques de negação de serviço contra produção",
      "Engenharia social de funcionários ou clientes",
      "Ataques físicos",
      "Achados teóricos sem prova de conceito",
      "Reports de scanners automáticos sem análise humana",
      "Problemas em dependências de terceiros (reporte ao fornecedor)",
    ],
    rewardHeading: "Programa de recompensa",
    rewardBody: (
      <p>
        Pré-GA: agradecimento no changelog, crédito no Hall of Fame e brindes
        CoreLink para achados MEDIUM+. Programa monetário planejado pós-GA.
      </p>
    ),
    morePolicyHref:
      "https://github.com/HumanGuardrail/corelink/blob/main/specs/_security/vulnerability-disclosure-policy.md",
    morePolicyLabel: "Leia a política completa (VDP-001)",
    securityTxtHref: "/.well-known/security.txt",
    securityTxtLabel: "security.txt (RFC 9116)",
    hallOfFameHref: "/security/hall-of-fame",
    hallOfFameLabel: "Hall of Fame",
  },
  es: {
    title: "Política de Seguridad",
    intro:
      "CoreLink opera un programa de divulgación coordinada de vulnerabilidades. Esta página es el resumen para clientes; el texto legal completo vive en nuestro repositorio de specs (enlace abajo).",
    reportHeading: "Cómo reportar",
    reportBody: (
      <>
        <p>
          Escribe a <code>security@humangr.com</code> con el prefijo{" "}
          <code>[VULN]</code> en el asunto. Para issues de alto impacto,
          cifra con nuestra clave PGP.
        </p>
        <p>
          No hay formulario web: el correo es el único canal de recepción.
        </p>
      </>
    ),
    slaHeading: "SLA de respuesta",
    slaIntro:
      "Tiempos en horas/días naturales desde la recepción de un reporte bien formado.",
    slaRows: [
      { stage: "Confirmación de recepción", target: "≤ 24 horas" },
      { stage: "Triaje inicial", target: "≤ 72 horas" },
      { stage: "Actualizaciones de estado", target: "cada 7 días" },
      { stage: "Crédito público (si lo deseas)", target: "en la divulgación coordinada" },
    ],
    severityHeading: "Severidad & SLA de parche",
    severityIntro:
      "Severidad mapeada desde CVSS v3.1 Base, con escalado automático ante violaciones de aislamiento de tenant.",
    severityRows: [
      { cvss: "9.0 – 10.0", severity: "CRÍTICA", patch: "≤ 24 horas" },
      { cvss: "7.0 – 8.9", severity: "ALTA", patch: "≤ 7 días" },
      { cvss: "4.0 – 6.9", severity: "MEDIA", patch: "≤ 30 días" },
      { cvss: "0.1 – 3.9", severity: "BAJA", patch: "≤ 90 días" },
    ],
    safeHarborHeading: "Safe harbor",
    safeHarborBody: (
      <p>
        No emprenderemos acciones legales contra investigadores que actúen de
        buena fe, eviten violaciones de privacidad, interactúen sólo con
        cuentas propias, no exploten más allá del PoC y nos den un tiempo
        razonable para corregir antes de la divulgación pública.
      </p>
    ),
    outOfScopeHeading: "Fuera de alcance",
    outOfScopeItems: [
      "Denegación de servicio contra producción",
      "Ingeniería social de personal o clientes",
      "Ataques físicos",
      "Hallazgos teóricos sin prueba de concepto",
      "Reportes generados por escáneres automáticos sin análisis humano",
      "Problemas en dependencias de terceros (reporta al proveedor)",
    ],
    rewardHeading: "Programa de recompensa",
    rewardBody: (
      <p>
        Pre-GA: agradecimiento en el changelog, crédito en el Hall of Fame y
        swag CoreLink para hallazgos MEDIUM+. Programa monetario planificado
        post-GA.
      </p>
    ),
    morePolicyHref:
      "https://github.com/HumanGuardrail/corelink/blob/main/specs/_security/vulnerability-disclosure-policy.md",
    morePolicyLabel: "Leer la política completa (VDP-001)",
    securityTxtHref: "/.well-known/security.txt",
    securityTxtLabel: "security.txt (RFC 9116)",
    hallOfFameHref: "/security/hall-of-fame",
    hallOfFameLabel: "Hall of Fame",
  },
  // R-prep i18n-de — `de` joined as the fourth canonical locale (DACH enterprise GA).
  // Native-speaker review pending; copy below is MT-quality bootstrap per
  // TRANSLATION-WORKFLOW.md SLA (≤ 14 d of EN change).
  de: {
    title: "Sicherheitsrichtlinie",
    intro:
      "CoreLink betreibt ein Programm zur koordinierten Offenlegung von Sicherheitslücken. Diese Seite ist die kundenorientierte Zusammenfassung; der vollständige rechtsverbindliche Text liegt in unserem Spec-Repository (Link unten).",
    reportHeading: "Wie melden",
    reportBody: (
      <>
        <p>
          E-Mail an <code>security@humangr.com</code> mit dem Betreff-Präfix{" "}
          <code>[VULN]</code>. Für Probleme mit hoher Auswirkung bitte mit
          unserem PGP-Schlüssel verschlüsseln.
        </p>
        <p>
          Es gibt kein Webformular: E-Mail ist der einzige Meldekanal.
        </p>
      </>
    ),
    slaHeading: "Antwort-SLA",
    slaIntro:
      "Zeiten in Kalenderstunden/-tagen ab Eingang eines korrekt formulierten Berichts.",
    slaRows: [
      { stage: "Empfangsbestätigung", target: "innerhalb von 24 Stunden" },
      { stage: "Erste Triage", target: "innerhalb von 72 Stunden" },
      { stage: "Statusupdates", target: "alle 7 Tage" },
      { stage: "Öffentliche Würdigung (falls gewünscht)", target: "bei koordinierter Offenlegung" },
    ],
    severityHeading: "Schweregrad & Patch-SLA",
    severityIntro:
      "Schweregrad abgeleitet vom CVSS v3.1 Base Score, mit automatischer Eskalation bei Verletzungen der Tenant-Isolation.",
    severityRows: [
      { cvss: "9,0 – 10,0", severity: "KRITISCH", patch: "≤ 24 Stunden" },
      { cvss: "7,0 – 8,9", severity: "HOCH", patch: "≤ 7 Tage" },
      { cvss: "4,0 – 6,9", severity: "MITTEL", patch: "≤ 30 Tage" },
      { cvss: "0,1 – 3,9", severity: "NIEDRIG", patch: "≤ 90 Tage" },
    ],
    safeHarborHeading: "Safe Harbor",
    safeHarborBody: (
      <p>
        Wir leiten keine rechtlichen Schritte gegen Sicherheitsforscher ein,
        die in gutem Glauben handeln, Datenschutzverletzungen vermeiden, nur
        mit eigenen Konten interagieren, keine Ausnutzung über den
        Proof-of-Concept hinaus betreiben und uns angemessene Zeit zur Behebung
        vor der Offenlegung geben. Vollständiger Wortlaut im Spec.
      </p>
    ),
    outOfScopeHeading: "Nicht im Geltungsbereich",
    outOfScopeItems: [
      "Denial-of-Service gegen die Produktivumgebung",
      "Social Engineering von Mitarbeitenden oder Kunden",
      "Physische Angriffe",
      "Theoretische Befunde ohne Proof-of-Concept",
      "Berichte von automatischen Scannern ohne menschliche Analyse",
      "Probleme in Drittanbieter-Abhängigkeiten (an den Anbieter melden)",
    ],
    rewardHeading: "Belohnungsprogramm",
    rewardBody: (
      <p>
        Vor GA: Dank im Changelog, Hall-of-Fame-Eintrag und CoreLink-Swag für
        Befunde der Stufe MEDIUM+. Geldprämien sind nach GA geplant.
      </p>
    ),
    morePolicyHref:
      "https://github.com/HumanGuardrail/corelink/blob/main/specs/_security/vulnerability-disclosure-policy.md",
    morePolicyLabel: "Vollständige Richtlinie lesen (VDP-001)",
    securityTxtHref: "/.well-known/security.txt",
    securityTxtLabel: "security.txt (RFC 9116)",
    hallOfFameHref: "/security/hall-of-fame",
    hallOfFameLabel: "Hall of Fame",
  },
};

export interface SecurityPolicyPageProps {
  locale: Locale;
}

// Token-driven rich-text scope for the localized JSX bodies (report / safe
// harbor / reward). `@tailwindcss/typography` is not installed, so descendant
// selectors supply the reading styles: body on `--t2`, code/links on `--t1`
// (both WCAG-AA on `--bg`). Tokens-only; no raw hex.
const RICHTEXT = [
  "text-sm leading-6 text-[var(--t2)]",
  "[&_p]:my-2 [&_p]:text-[var(--t2)]",
  "[&_a]:text-[var(--t1)] [&_a]:underline [&_a]:decoration-[var(--line-2)] [&_a]:underline-offset-2 hover:[&_a]:decoration-[var(--t2)]",
  "[&_code]:rounded-[var(--r-chip)] [&_code]:bg-[rgba(255,255,255,0.06)] [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[0.9em] [&_code]:text-[var(--t1)]",
].join(" ");

const H2 = "text-base font-[560] tracking-[-0.012em] text-[var(--t1)]";
const TABLE = "w-full border-collapse text-sm";
const TH =
  "border-b border-[var(--line)] px-3 py-2 text-left font-[510] text-[var(--t3)]";
const TD = "border-b border-[var(--line)] px-3 py-2 text-[var(--t2)]";

export function SecurityPolicyPage({ locale }: SecurityPolicyPageProps) {
  const t = COPY[locale];
  return (
    <PublicShell width="prose">
      <PublicPageHeader title={t.title} />
      <p className="mb-6 text-sm leading-6 text-[var(--t2)]">{t.intro}</p>

      <div className="flex flex-col gap-4">
        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.reportHeading}</h2>
          <div className={RICHTEXT}>{t.reportBody}</div>
        </Card>

        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.slaHeading}</h2>
          <p className="mb-3 text-sm text-[var(--t2)]">{t.slaIntro}</p>
          <table className={TABLE}>
            <thead>
              <tr>
                <th className={TH}>Stage</th>
                <th className={TH}>Target</th>
              </tr>
            </thead>
            <tbody>
              {t.slaRows.map((r) => (
                <tr key={r.stage}>
                  <td className={TD}>{r.stage}</td>
                  <td className={TD}>{r.target}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>

        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.severityHeading}</h2>
          <p className="mb-3 text-sm text-[var(--t2)]">{t.severityIntro}</p>
          <table className={TABLE}>
            <thead>
              <tr>
                <th className={TH}>CVSS</th>
                <th className={TH}>Severity</th>
                <th className={TH}>Patch SLA</th>
              </tr>
            </thead>
            <tbody>
              {t.severityRows.map((r) => (
                <tr key={r.severity}>
                  <td className={`${TD} font-mono text-[var(--t1)]`}>{r.cvss}</td>
                  <td className={`${TD} font-[560] text-[var(--t1)]`}>{r.severity}</td>
                  <td className={TD}>{r.patch}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </Card>

        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.safeHarborHeading}</h2>
          <div className={RICHTEXT}>{t.safeHarborBody}</div>
        </Card>

        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.outOfScopeHeading}</h2>
          <ul className="list-disc pl-6 text-sm text-[var(--t2)] marker:text-[var(--t3)]">
            {t.outOfScopeItems.map((item) => (
              <li key={item} className="my-1">
                {item}
              </li>
            ))}
          </ul>
        </Card>

        <Card>
          <h2 className={`mb-2 ${H2}`}>{t.rewardHeading}</h2>
          <div className={RICHTEXT}>{t.rewardBody}</div>
        </Card>
      </div>

      <nav className="mt-8 border-t border-[var(--line)] pt-4 text-sm">
        <ul className="flex flex-col gap-1">
          <li>
            <a
              href={t.morePolicyHref}
              className="text-[var(--t1)] underline decoration-[var(--line-2)] underline-offset-2 hover:decoration-[var(--t2)]"
            >
              {t.morePolicyLabel}
            </a>
          </li>
          <li>
            <a
              href={t.securityTxtHref}
              className="text-[var(--t1)] underline decoration-[var(--line-2)] underline-offset-2 hover:decoration-[var(--t2)]"
            >
              {t.securityTxtLabel}
            </a>
          </li>
          <li>
            <a
              href={t.hallOfFameHref}
              className="text-[var(--t1)] underline decoration-[var(--line-2)] underline-offset-2 hover:decoration-[var(--t2)]"
            >
              {t.hallOfFameLabel}
            </a>
          </li>
        </ul>
      </nav>
    </PublicShell>
  );
}
