import { describe, expect, it, vi } from "vitest";
import handler, { handleDsrAlert } from "../src/index.js";
import { constantTimeBearerMatches, parseDsrAlertEnvelope, type DsrAlertReceiverEnv } from "../src/contract.js";
const token = "a".repeat(32), eventId = `dsr-erasure-dlq:${"a".repeat(64)}`;
const envelope = { schema_version: 1, event: "dsr.erasure.dead_letter", severity: "critical", component: "dsr-erasure-dlq", event_id: eventId, exhausted: true, requeue_count: 1 } as const;
type Row = { event_id: string; schema_version: number; event: string; severity: string; component: string; exhausted: number; requeue_count: number };
function fakeDb(options: { fail?: boolean; ambiguous?: boolean; missing?: boolean } = {}) {
  const rows = new Map<string, Row>(), writes: unknown[][] = [];
  const prepare = vi.fn().mockImplementation(() => ({ bind: vi.fn().mockImplementation((...values: unknown[]) => ({
    run: vi.fn().mockImplementation(async () => { writes.push(values); if (options.fail) throw new Error("secret-bearing storage error"); if (options.ambiguous) return { success: true, meta: { changes: 2 } }; const id = values[0] as string; if (rows.has(id)) return { success: true, meta: { changes: 0 } }; rows.set(id, { event_id: id, schema_version: values[1] as number, event: values[2] as string, severity: values[3] as string, component: values[4] as string, exhausted: values[5] as number, requeue_count: values[6] as number }); return { success: true, meta: { changes: 1 } }; }),
    first: vi.fn().mockImplementation(async () => options.missing ? null : rows.get(values[0] as string) ?? null),
  })) }));
  return { db: { prepare } as unknown as D1Database, rows, writes, prepare };
}
function request(body: unknown = envelope, options: { method?: string; auth?: string; contentType?: string; path?: string } = {}): Request { return new Request(`https://receiver.invalid${options.path ?? "/"}`, { method: options.method ?? "POST", headers: { authorization: options.auth ?? `Bearer ${token}`, "content-type": options.contentType ?? "application/json" }, body: options.method === "GET" ? undefined : JSON.stringify(body) }); }
function environment(overrides: Partial<DsrAlertReceiverEnv> = {}, options: Parameters<typeof fakeDb>[0] = {}) { const database = fakeDb(options); return { env: { DSR_ALERT_RECEIVER_TOKEN: token, ALERT_RECEIPTS_DB: database.db, ...overrides }, database }; }
describe("DSR alert receiver", () => {
  it("persists the closed sender envelope before a 2xx and deduplicates replay", async () => { const r = environment(); expect((await handleDsrAlert(request(), r.env, () => 1789000000000)).status).toBe(202); const replay = await handleDsrAlert(request(), r.env); expect(replay.status).toBe(202); expect(await replay.json()).toEqual({ accepted: true, duplicate: true }); expect(r.database.rows).toHaveLength(1); expect(r.database.writes[0]).toEqual([eventId, 1, "dsr.erasure.dead_letter", "critical", "dsr-erasure-dlq", 1, 1, 1789000000000]); });
  it("rejects wrong method, auth, content type, protocol, path, and unavailable storage", async () => { const r = environment(); expect((await handleDsrAlert(request(envelope, { method: "GET" }), r.env)).status).toBe(405); expect((await handleDsrAlert(request(envelope, { auth: "Bearer wrong" }), r.env)).status).toBe(401); expect((await handleDsrAlert(request(envelope, { contentType: "text/plain" }), r.env)).status).toBe(415); expect((await handleDsrAlert(new Request("http://receiver.invalid/", { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(envelope) }), r.env)).status).toBe(400); expect((await handleDsrAlert(request(envelope, { path: "/bad" }), r.env)).status).toBe(404); expect((await handleDsrAlert(request(), { DSR_ALERT_RECEIVER_TOKEN: token })).status).toBe(503); expect(r.database.writes).toHaveLength(0); });
  it("rejects malformed and extra identity fields without a receipt", async () => { const r = environment(); for (const value of [{ ...envelope, event_id: "not-opaque" }, { ...envelope, requeue_count: 2 }, { ...envelope, subject_id: "PII" }, { ...envelope, exhausted: false }]) expect((await handleDsrAlert(request(value), r.env)).status).toBe(400); expect(r.database.writes).toHaveLength(0); });
  it("fails closed for D1 error, ambiguous write, and absent post-write receipt without logging", async () => { const error = vi.spyOn(console, "error").mockImplementation(() => undefined); expect((await handleDsrAlert(request(), environment({}, { fail: true }).env)).status).toBe(503); expect((await handleDsrAlert(request(), environment({}, { ambiguous: true }).env)).status).toBe(503); expect((await handleDsrAlert(request(), environment({}, { missing: true }).env)).status).toBe(503); expect(error).not.toHaveBeenCalled(); error.mockRestore(); });
  it("uses bearer comparison and only the Worker fetch interface", async () => { expect(constantTimeBearerMatches(`Bearer ${token}`, token)).toBe(true); expect(constantTimeBearerMatches(`Bearer ${"b".repeat(32)}`, token)).toBe(false); expect(parseDsrAlertEnvelope(envelope)).toEqual(envelope); expect((await handler.fetch!(request(), environment().env)).status).toBe(202); });
});
