/// **Every** live, tenant-scoped D1 table (keyed by `tenant_id`, `namespace`,
/// or an opaque principal id), derived from `migrations/d1/*.sql`. Transient
/// table-rebuild artifacts (`*_new`, immediately `DROP`+`RENAME`'d away by
/// migr. 0062/0064) are excluded.
///
/// **CF-1 invariant:** every entry here MUST be classified into EXACTLY ONE of
/// {erase-set, namespace-set, retain-set, CAS-plane-owned, special} — enforced
/// fail-closed by [`super::ensure_tenant_keyed_tables_classified`] before any D1
/// work. AND cross-checked against the migrations on disk by the
/// `every_migrated_tenant_keyed_table_is_classified` test. A FUTURE tenant-keyed
/// migration therefore cannot silently escape erasure classification.
pub(super) const ALL_TENANT_KEYED_TABLES: &[&str] = &[
    // erase-set (tenant_id)
    "stripe_checkout_ownership_ledger",
    "tier_selections",
    "tenant_billing",
    "pilot_signups",
    "devenv_credential_obligation",
    "runner_credential_obligation",
    "tenant_credential_revocation_floor",
    "credential_generation_revocation",
    "credential_generation_event_receipts",
    "pat",
    "usage_counter",
    "tenant_storage_state",
    "tenant_offboarding_state",
    "usage_event_staging",
    "usage_event_staging_conflicts",
    "dpa_acceptance_pending",
    "tenant_config",
    "hot_blobs",
    "quota_reservations",
    "audit_drain_lease", // audit-drain partition lease (migr. 0101, B-038) — erase:tenant_id
    "quota_cas_attempts",
    "quota_fsm_state",
    "ratelimit_buckets",
    "byok_envelope",
    "tenant_byok_config",
    "tenant_byok_secret",
    "tenant_byok_config_history",
    "tenant_byok_secret_history",
    "byok_activation_key_health",
    "byok_activation_source_object",
    "byok_activation_source_capture",
    "byok_transition_commit_guard",
    "byok_control_outcome",
    "byok_backfill_run",
    "byok_logical_object_generation",
    "byok_logical_object_publication",
    "byok_purge_identity_quarantine",
    "byok_object_purge_item",
    "byok_activation_intent",
    "byok_activation_guard",
    "byok_tenant_gate",
    "byok_data_intent",
    "byok_transition_fence",
    "adapter_oci_kv",
    "survey_responses",
    "tenant_quota",
    "githugr_tenant_org_map",
    "team_member",
    "cas_tombstone",
    "pilot_tenants",
    "runners_entitlement",
    // Runner entitlement reconciliation fence (migr. 0139/0140) is
    // tenant-scoped operational ordering state; erase it with its tenant.
    "runner_entitlement_reconcile_fence",
    "monthly_request_counts",
    "tier_selection_locks",
    "stripe_checkout_sessions",
    "runner_billing",
    "runner_checkout_attempts",
    "gc_run",
    "gc_candidates",
    "region_migration_request",
    "region_migration_progress",
    "tenant_org_map",
    "tenant_gh_installation_map",
    "runner_repo_allowlist",
    "workspaces",
    "usage_daily",
    "runner_usage_counter",
    "devenv_monthly_vcpu",
    "gc_purge_intent",
    "cas_write_intent",
    "cas_reconciliation_intent",
    "storage_mutation_liability",
    // erase-set (namespace)
    "adapter_cache_map",
    "adapter_npm_meta",
    "adapter_pip_index",
    // retain-set
    "dsr_erasure_log",
    "dsr_requested",
    "dsr_tickets",
    // Migration 0145's redrive envelope is short-lived recovery authority,
    // not ordinary tenant operational state: preserving it through the DSR
    // lets the bounded one-time retry complete and keeps its operator/approval
    // references associated with the transition audit. The worker removes
    // the envelope and linked audit rows together at the frozen seven-day TTL
    // (issue #2166); this is a bounded accountability exception under
    // ADR-S11-013, not indefinite subject-data retention.
    "dsr_dlq_redrive_envelopes",
    "dpa_acceptances",
    "erasure_attestations",
    "audit_outbox",
    "stripe_customers",
    "stripe_subscriptions",
    "stripe_invoices",
    "stripe_disputes",
    "stripe_refunds",
    "billing_replay_audit",
    "stripe_idempotency_keys",
    "billing_reconciliation_drift",
    "stripe_submission_state",
    "customer_audit_events",
    "audit_chain_head",
    "audit_chain_epoch_ledger",
    "audit_chain_epoch",
    "audit_chain_archive_manifest",
    "audit_chain_legacy_tail_resolution",
    "audit_chain_witness_receipt",
    "tier_select_audit_events",
    "stripe_billing_audit_events",
    "runner_period_terms_snapshot",
    "runner_aggregate_event_claim",
    "sla_monthly_observations",
    "sla_monthly_measurements",
    "sla_credit_ledger",
    "tenant_legal_hold",
    "cas_retention",
    "abuse_score_history",
    "session_exchange_throttle",
    // Migration 0151's exact-run staging ownership marker is append-only:
    // its UPDATE/DELETE triggers preserve the synthetic-tenant witness for
    // staging load-test reconciliation, so the DSR registry retains it too.
    "staging_load_test_synthetic_tenants",
    // CAS-plane-owned
    "blob_meta",
    "ac_meta",
    "chunks",
    "manifest_chunks",
    "multipart_sessions",
    // special
    "byok_activation_worker_assertion",
    "byok_activation_operation_guard",
    "byok_activation_postcondition",
    "byok_activation_suspension_postcondition",
    "byok_activation_transition_assertion",
    "clerk_provisioning_lock",
    "signup_orchestration",
    "signup_attempts",
    "tenant",
];
